[package]
name = "goblinsan/core-interactions"
version = "1.0.0"
description = "Core interactions with Knit, Promise, and Signal dependencies"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@^1.5.1"
promise = "evaera/promise@^4.0.0"
signal = "sleitnick/signal@^2.0.3"
